In [1]:
import numpy as np

In [3]:
A = np.array([[1, 0, 0],
              [0, 0, 0],
              [0, 0, 0]])

B = np.random.normal(0,1, size=(3,3))

print(A, B)
print(A.dot(B))

(array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]), array([[-0.28645433,  0.1442658 ,  0.34891201],
       [-0.33808471,  1.79930981, -0.43479648],
       [ 0.19347096,  0.16500705,  0.4607569 ]]))
[[-0.28645433  0.1442658   0.34891201]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [4]:
A = np.array([[0, 1, 0],
              [0, 0, 0],
              [0, 0, 0]])

B = np.random.normal(0,1, size=(3,3))

print(A, B)
print(A.dot(B))

(array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]]), array([[ 1.32730731, -2.23600924,  0.89704818],
       [ 0.97802829,  1.40530546, -0.03513659],
       [-0.15817001,  1.22569032,  0.88325052]]))
[[ 0.97802829  1.40530546 -0.03513659]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [5]:
A = np.array([[0, 0, 0],
              [1, 0, 0],
              [0, 0, 0]])

B = np.random.normal(0,1, size=(3,3))

print(A, B)
print(A.dot(B))

(array([[0, 0, 0],
       [1, 0, 0],
       [0, 0, 0]]), array([[-0.90399887,  1.18177827,  0.50625114],
       [ 0.17364774, -2.05233277,  0.05209824],
       [ 1.94656886,  1.02152303,  0.36937148]]))
[[ 0.          0.          0.        ]
 [-0.90399887  1.18177827  0.50625114]
 [ 0.          0.          0.        ]]


In [6]:
A = np.array([[0, 0, 0],
              [0, 1, 0],
              [0, 0, 0]])

B = np.random.normal(0,1, size=(3,3))

print(A, B)
print(A.dot(B))

(array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]]), array([[-0.87662293, -0.81767991, -1.61837809],
       [-1.58060746,  1.23273908,  0.15382257],
       [ 1.35602548, -0.55721665, -1.14708891]]))
[[ 0.          0.          0.        ]
 [-1.58060746  1.23273908  0.15382257]
 [ 0.          0.          0.        ]]
